obstacle_range: 5.5
raytrace_range: 6.0

footprint: [[0.4215, -0.262], [0.4215, 0.262], [-0.4215, 0.262], [-0.4215, -0.262]]

publish_frequency: 1.0
transform_tolerance: 0.7 # Costmap tolerance

inflation_layer:
  inflation_radius: 0.5

obstacle_layer:
  observation_sources: front_scan rear_scan
  front_scan: {data_type: LaserScan, topic: /summit_xl/front_laser/scan, marking: true, clearing: true}
  rear_scan: {data_type: LaserScan, topic: /summit_xl/rear_laser/scan, marking: true, clearing: true}
