global_costmap:
  global_frame: /summit_xl_map
  robot_base_frame: /summit_xl_base_link
  update_frequency: 2.0 # Map update loop
  plugins:
      - name: static_map
        type: "costmap_2d::StaticLayer"
      -
        name: obstacle_layer
        type: "costmap_2d::VoxelLayer"
      -
        name: costmap_prohibition_layer
        type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"
      -
        name: inflation_layer
        type: "costmap_2d::InflationLayer"

  static_map:
      lethal_cost_threshold: 50
      static_map: true
