local_costmap:
  global_frame: /summit_xl_odom
  robot_base_frame: /summit_xl_base_link
  update_frequency: 2.0 # Map update loop
  static_map: false
  rolling_window: true
  #width: 6.0
  #height: 6.0
  #resolution: 0.01 #0.05
  width: 8.0 #5
  height: 8.0 #5
  resolution: 0.05 #0.05

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0
  plugins:
      -
        name: obstacle_layer
        type: "costmap_2d::VoxelLayer"
      -
        name: inflation_layer
        type: "costmap_2d::InflationLayer"
